import { NextResponse } from "next/server";
import { LIFE_NO_STORE_HEADERS, authorizeLifeRequest, lifeJsonError, readJsonBody } from "@/lib/server/life-api";
import { resolveFixedLifeIdentity } from "@/lib/server/fixed-life-auth";
import { createLifeReminder, listLifeReminders, updateLifeReminder } from "@/lib/server/life-reminder-center";

function actor(request:Request){return resolveFixedLifeIdentity(request)?.partnerKey??null;}
function fail(error:unknown){return lifeJsonError(error instanceof Error?error.message:"提醒中心暂时不可用",502,"REMINDER_CENTER_ERROR");}

export async function GET(request:Request){const auth=await authorizeLifeRequest(request);if(auth)return auth;const a=actor(request);if(!a)return lifeJsonError("请先登录",401,"UNAUTHORIZED");try{return NextResponse.json({ok:true,items:await listLifeReminders(a,true)},{headers:LIFE_NO_STORE_HEADERS});}catch(e){return fail(e);}}
export async function POST(request:Request){const auth=await authorizeLifeRequest(request);if(auth)return auth;const a=actor(request);if(!a)return lifeJsonError("请先登录",401,"UNAUTHORIZED");const parsed=await readJsonBody(request);if(!parsed.ok)return parsed.response;const v=parsed.value;const recipientScope=v?.recipientScope;const title=typeof v?.title==="string"?v.title.trim():"";const content=typeof v?.content==="string"?v.content.trim():"";const dueAt=typeof v?.dueAt==="string"?v.dueAt:"";if(!["cat","fish","both"].includes(recipientScope)||!title||!dueAt||Number.isNaN(Date.parse(dueAt)))return lifeJsonError("提醒内容不完整",400,"INVALID_REMINDER");try{return NextResponse.json({ok:true,item:await createLifeReminder(a,{recipientScope,title,content,dueAt})},{headers:LIFE_NO_STORE_HEADERS});}catch(e){return fail(e);}}
export async function PATCH(request:Request){const auth=await authorizeLifeRequest(request);if(auth)return auth;const a=actor(request);if(!a)return lifeJsonError("请先登录",401,"UNAUTHORIZED");const parsed=await readJsonBody(request);if(!parsed.ok)return parsed.response;const v=parsed.value;const id=typeof v?.id==="string"?v.id:"";const action=v?.action;const snoozeUntil=typeof v?.snoozeUntil==="string"?v.snoozeUntil:null;if(!id||!["complete","dismiss","snooze"].includes(action))return lifeJsonError("提醒操作无效",400,"INVALID_REMINDER_ACTION");try{return NextResponse.json({ok:true,item:await updateLifeReminder(a,{id,action,snoozeUntil})},{headers:LIFE_NO_STORE_HEADERS});}catch(e){return fail(e);}}
