"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { AppPageShell } from "@/components/ui/AppPageShell";
import { useLifeIdentity } from "@/components/life/LifeIdentityContext";

type Item={id:string;recipient:"cat"|"fish";sourceKind:string;title:string;content:string|null;dueAt:string;status:"pending"|"snoozed"|"completed"|"dismissed";snoozedUntil:string|null};
export function LifeReminderCenterPage(){const {currentPartnerKey}=useLifeIdentity();const [items,setItems]=useState<Item[]>([]);const [title,setTitle]=useState("");const [due,setDue]=useState("");const [scope,setScope]=useState<"cat"|"fish"|"both">("both");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const load=useCallback(async()=>{const r=await fetch("/api/life/reminders",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"读取提醒失败");setItems(Array.isArray(b.items)?b.items:[]);},[]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
const active=useMemo(()=>items.filter(i=>i.status==="pending"||i.status==="snoozed"),[items]);const done=useMemo(()=>items.filter(i=>i.status==="completed"),[items]);
async function create(){if(!title.trim()||!due)return;setBusy(true);setError("");try{const r=await fetch("/api/life/reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientScope:scope,title:title.trim(),dueAt:new Date(due).toISOString()})});const b=await r.json();if(!r.ok)throw new Error(b.error||"创建失败");setTitle("");setDue("");await load();}catch(e){setError(e instanceof Error?e.message:"创建失败");}finally{setBusy(false);}}
async function act(id:string,action:"complete"|"dismiss"|"snooze"){const snoozeUntil=action==="snooze"?new Date(Date.now()+60*60*1000).toISOString():null;const r=await fetch("/api/life/reminders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action,snoozeUntil})});if(r.ok)await load();}
return <AppPageShell title="提醒中心"><div className="grid gap-3"><section className="life-surface rounded-[var(--life-radius-card)] p-4"><p className="text-sm font-extrabold">新建提醒</p><div className="mt-3 grid gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：交水费" className="rounded-2xl border border-[var(--life-border-soft)] bg-white/80 px-3.5 py-3 text-sm"/><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} className="rounded-2xl border border-[var(--life-border-soft)] bg-white/80 px-3.5 py-3 text-sm"/><div className="flex gap-2">{(["cat","fish","both"] as const).map(v=><button key={v} onClick={()=>setScope(v)} className={`rounded-full px-3 py-2 text-xs font-bold ${scope===v?"bg-[var(--life-teal)] text-white":"bg-white/70"}`}>{v==="cat"?"小猫":v==="fish"?"小鱼":"两个人"}</button>)}</div><button disabled={busy||!title.trim()||!due} onClick={()=>void create()} className="rounded-full bg-[var(--life-teal)] px-4 py-2.5 text-sm font-extrabold text-white disabled:opacity-40">{busy?"保存中…":"添加提醒"}</button></div>{error?<p className="mt-2 text-xs text-[var(--life-danger)]">{error}</p>:null}</section><section className="life-surface rounded-[var(--life-radius-card)] p-4"><p className="text-sm font-extrabold">接下来</p><div className="mt-3 grid gap-2">{active.length?active.map(i=><div key={i.id} className="rounded-2xl bg-white/65 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-bold">{i.title}</p><p className="mt-1 text-[10px] text-[var(--life-text-muted)]">{new Date(i.snoozedUntil||i.dueAt).toLocaleString("zh-CN")} · {i.sourceKind==="medicine"?"药箱":"自定义"}</p></div><span className="text-xs">{i.recipient===currentPartnerKey?"我":"Ta"}</span></div><div className="mt-2 flex gap-2"><button onClick={()=>void act(i.id,"complete")} className="text-xs font-bold text-[var(--life-teal-strong)]">完成</button><button onClick={()=>void act(i.id,"snooze")} className="text-xs font-bold text-[var(--life-text-muted)]">1小时后</button><button onClick={()=>void act(i.id,"dismiss")} className="text-xs font-bold text-[var(--life-text-muted)]">忽略</button></div></div>):<p className="text-xs text-[var(--life-text-muted)]">暂时没有待提醒的事情。</p>}</div></section>{done.length?<section className="life-surface rounded-[var(--life-radius-card)] p-4"><p className="text-sm font-extrabold">已完成</p><p className="mt-2 text-xs text-[var(--life-text-muted)]">共 {done.length} 条</p></section>:null}</div></AppPageShell>}
